const INIT = "FECTHING_INIT";
const SUCCESS = "FECTHING_SUCCESS";
const FAILURE = "FECTHING_FAILURE";
const SEARCH = "SEARCH";
const SEARCH1 = "SEARCH1";
const FILTER_STOCK = "FILTER_STOCK";
const SORT = "SORT";
const DEFAULT_ORDER = "DEFAULT_ORDER";

export {
	INIT,
	SUCCESS,
	FAILURE,
	SEARCH,
	SEARCH1,
	FILTER_STOCK,
	SORT,
	DEFAULT_ORDER,
};
