const INIT = "FECTHING_INIT";
const SUCCESS = "FECTHING_SUCCESS";
const FAILURE = "FECTHING_FAILURE";
const SEARCH = "SEARCH";
const FILTER_STOCK = "FILTER_STOCK";
const SORT = "SORT";
const DEFAULT_ORDER = "DEFAULT_ORDER";

export { INIT, SUCCESS, FAILURE, SEARCH, FILTER_STOCK, SORT, DEFAULT_ORDER };
